import { ArrowUpRight, Check, Copy, Gift, Heart, Instagram, Link as LinkIcon, Percent, Sparkles, Users } from "lucide-react";
import { useState } from "react";
import { PageIntro, SiteLayout } from "@/components/site/SiteLayout";
import { toast } from "sonner";

const benefits = [{ icon: Percent, title: "12% de comissão", copy: "Em cada pedido atribuído ao seu código." }, { icon: Gift, title: "Mimos para criar", copy: "Receba produtos para testar e contar a sua verdade." }, { icon: Users, title: "Comunidade VELA", copy: "Acesso a encontros, conteúdos e lançamentos." }];

export default function Influencers() {
  const [submitted, setSubmitted] = useState(false);
  const [copied, setCopied] = useState(false);
  const copy = () => { navigator.clipboard?.writeText("MARINA12"); setCopied(true); toast.success("Cupom copiado: MARINA12"); setTimeout(() => setCopied(false), 1800); };
  return <SiteLayout><PageIntro eyebrow="VELA creators" title="Influencie com intenção." description="Para quem transforma indicação em conversa, e conversa em uma relação mais bonita com a beleza." /><section className="influencer-hero container"><div className="influencer-hero-copy"><span className="creator-tag"><Sparkles size={14} /> programa aberto</span><h2>Seu olhar<br /><em>tem valor.</em></h2><p>Você não precisa falar de tudo. Só do que realmente faz parte do seu ritual — e a gente cuida do resto.</p><a href="#inscricao" className="button button-dark">Quero fazer parte <ArrowUpRight size={17} /></a></div><div className="influencer-art"><img src="https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=1100&q=88" alt="Cosméticos VELA em luz natural" /><div className="influencer-art-note">uma beleza<br /><strong>sem roteiro.</strong></div></div></section><section className="creator-benefits container">{benefits.map(({ icon: Icon, title, copy }) => <div className="benefit-card" key={title}><Icon size={20} /><h3>{title}</h3><p>{copy}</p></div>)}</section><section className="coupon-demo"><div className="container coupon-inner"><div><p className="eyebrow light">Uma amostra do ritual</p><h2>Seu cupom pode<br /><em>começar assim.</em></h2><p>Quem chegar pelo seu link ganha 10% no primeiro pedido.</p></div><div className="coupon-card"><div className="coupon-avatar">MA</div><div><span>cupom da criadora</span><strong>MARINA12</strong><small>10% OFF na primeira compra</small></div><button onClick={copy} aria-label="Copiar cupom">{copied ? <Check size={17} /> : <Copy size={17} />}</button></div></div></section><section className="influencer-form-section container" id="inscricao"><div><p className="eyebrow">Agora é com você</p><h2>Vamos criar algo<br /><em>honesto.</em></h2><p>Conta um pouco sobre você. A equipe VELA responde em até 3 dias úteis.</p><div className="form-social"><Instagram size={17} /> @vela.beauty · <LinkIcon size={17} /> vela.beauty/creators</div></div>{submitted ? <div className="form-success"><div><Check size={24} /></div><h3>Recebemos seu ritual.</h3><p>Em breve você recebe uma mensagem no e-mail informado.</p></div> : <form className="creator-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><label>Seu nome<input required placeholder="Como podemos te chamar?" /></label><label>Seu melhor e-mail<input type="email" required placeholder="voce@email.com" /></label><label>Onde você cria?<select defaultValue=""><option value="" disabled>Escolha uma rede</option><option>Instagram</option><option>TikTok</option><option>YouTube</option><option>Blog / newsletter</option></select></label><label>Link do seu perfil<input required placeholder="instagram.com/voce" /></label><button className="button button-dark" type="submit">Enviar inscrição <ArrowUpRight size={17} /></button></form>}</section></SiteLayout>;
}
